services:
  timesheet-db:
    container_name: timesheet-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=loco
      - POSTGRES_PASSWORD=loco
      - POSTGRES_DB=timesheet_development
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: docker.io/bitnami/redis:7.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
